### PR TITLE
Make shortcutHeader command maintain the cursor's relative position

### PR DESCRIPTION
**Pull request by jonmseaman**

### CODE REVIEW

**Comment by jonmseaman** [comment]
Hey, thanks for making this plugin! I started using Obsidian, and I'm used to OneNote, which has this feature.
This is an enhancement to keep the cursor's position, which is the same as it is in OneNote.

**Comment by jonmseaman** [comment]
I am making a new pull request that also allows updating multiple lines.

**Comment by jonmseaman** [comment]
Oops, you can just use the same pull request.

**Comment by jonmseaman** [comment]
This fixes #5

**Comment by ryjjin** [comment]
Sorry for my long answer!
Thanks for your great work. 

I don't can use multiple lines for: 

- shortcutHeader, if multiple lines are selected via left alt (only if multiple lines of text are selected as a solid chunk)
- `code fences` (it works with left alt, but work incorrect for solid chunk selecting).

Anyway, it's great, i merge it and try to fix the remaining part

**Pull request merged**
